# Generated by Django 3.0.7 on 2020-06-16 07:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_auto_20200616_0755'),
    ]

    operations = [
        migrations.AlterField(
            model_name='schedulecall',
            name='site_url',
            field=models.URLField(),
        ),
    ]
